FROM registry.access.redhat.com/rhel-atomic
MAINTAINER abhijit.bhadra@ca.com


### Atomic/OpenShift Labels - https://github.com/projectatomic/ContainerApplicationGenericLabels
LABEL name="ca/umagent" \
      vendor="CA Inc" \
      version="1.0" \
      release="1" \
      summary="CA Inc's Monitoring app for Openshift" \
      description="Monitoring app will do ....." \
### Required labels above - recommended below
      url="https://www.ca.com" \
      run='docker run -tdi --name ${NAME} ${IMAGE}' \
      io.k8s.description="Monitor app will do ....." \
      io.k8s.display-name="Monitor app" \
      io.openshift.expose-services="" \
      io.openshift.tags="ca,monitor"

### Atomic Help File - Write in Markdown, it will be converted to man format at build time.
### https://github.com/projectatomic/container-best-practices/blob/master/creating/help.adoc
COPY help.md /

### add licenses to this directory
COPY licenses /licenses

### Setup user for build execution and application runtime
ENV APP_ROOT=/opt/app-root \
    USER_NAME=nobody \
    USER_UID=99
ENV APP_HOME=${APP_ROOT}/src  PATH=$PATH:${APP_ROOT}/bin

RUN microdnf --enablerepo=rhel-7-server-rpms --enablerepo=rhel-7-server-optional-rpms --enablerepo=rhel-7-server-extras-rpms \
    install --nodocs golang-github-cpuguy83-go-md2man \
      net-tools \
      cronie \
      docker-client && microdnf clean all


### Add necessary Red Hat repos here
    go-md2man -in /help.md -out /help.1 && \
#    useradd -l -u ${USER_UID} -r -g 0 -d ${APP_ROOT} -s /sbin/nologin \
#      -c "${USER_NAME} application user" ${USER_NAME} && #\
    microdnf clean all

curl -L -o  https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz && tar -xf docker-1.13.1.tgz


#RUN mkdir -p /usr/local/openshift && yum install -y wget net-tools cronie && wget https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz && tar -xf docker-1.13.1.tgz
RUN mkdir -p /usr/local/openshift/umagent
#RUN cp ./docker/docker /usr/bin/
ADD ./OpenshiftMonitor.tar.gz /usr/local/openshift/umagent
ADD ./run.sh /usr/local/openshift/umagent
RUN chmod +x /usr/local/openshift/umagent/run.sh
USER 99
WORKDIR /usr/local/openshift/umagent
CMD ["bash","run.sh"]

